"""Exact weak-amplitude transfer generated by the first two mode shells.

The fast audit checks the persisted closed forms.  Passing ``--derive``
reconstructs the order-six coefficient from the Fourier Navier-Stokes
Duhamel hierarchy; that symbolic derivation takes a few minutes.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import sympy as sp


COUNTEREXAMPLE_SCRIPT = Path(__file__).with_name(
    "quartic_transfer_counterexample.py"
)
SPEC = importlib.util.spec_from_file_location(
    "weak_generated_transfer_helpers", COUNTEREXAMPLE_SCRIPT
)
assert SPEC is not None and SPEC.loader is not None
HELPERS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(HELPERS)


def closed_forms() -> dict[str, sp.Expr]:
    x = sp.symbols("x", positive=True)
    seed_four = (1 - x) ** 2 * (x**3 + 2 * x**2 + 3 * x - 11) / 120
    difference_six = (
        (1 - x) ** 2 * (17 * x**3 + 34 * x**2 + 51 * x + 263) / 4800
    )
    sum_polynomial = (
        80 * x**11
        + 160 * x**10
        + 240 * x**9
        + 495 * x**8
        + 750 * x**7
        + 1005 * x**6
        + 1260 * x**5
        + 1515 * x**4
        + 1249 * x**3
        + 983 * x**2
        + 717 * x
        + 521
    )
    sum_six = (1 - x) ** 2 * sum_polynomial / 3360000
    interaction_six = -(
        (1 - x) ** 2 * (5 * x**3 + 10 * x**2 + 15 * x + 1) / 9600
    )
    interaction_eight = (
        (1 - x) ** 2
        * (
            25 * x**6
            + 50 * x**5
            + 75 * x**4
            + 44 * x**3
            + 48 * x**2
            + 52 * x
            + 56
        )
        / 490000
    )
    first_generation_six_polynomial = (
        80 * x**11
        + 160 * x**10
        + 240 * x**9
        + 495 * x**8
        + 750 * x**7
        + 1005 * x**6
        + 1260 * x**5
        + 1515 * x**4
        + 11399 * x**3
        + 21283 * x**2
        + 31167 * x
        + 184271
    )
    first_generation_six = (
        (1 - x) ** 2 * first_generation_six_polynomial / 3360000
    )
    second_generation_six_polynomial = (
        3640 * x**11
        + 7280 * x**10
        + 10920 * x**9
        + 23335 * x**8
        + 35750 * x**7
        + 48165 * x**6
        + 60580 * x**5
        + 72995 * x**4
        + 45931 * x**3
        + 18867 * x**2
        - 8197 * x
        + 11213799
    )
    second_generation_six = (
        (1 - x) ** 2 * second_generation_six_polynomial / 393120000
    )
    total_six_polynomial = (
        6500 * x**11
        + 13000 * x**10
        + 19500 * x**9
        + 40625 * x**8
        + 61750 * x**7
        + 82875 * x**6
        + 104000 * x**5
        + 125125 * x**4
        + 689807 * x**3
        + 1254489 * x**2
        + 1819171 * x
        + 16386753
    )
    total_six = (1 - x) ** 2 * total_six_polynomial / 196560000
    return {
        "x": x,
        "seed_four": seed_four,
        "difference_six": difference_six,
        "sum_six": sum_six,
        "interaction_six": interaction_six,
        "interaction_eight": interaction_eight,
        "first_generation_six": first_generation_six,
        "second_generation_six": second_generation_six,
        "total_six": total_six,
        "first_generation_six_polynomial": first_generation_six_polynomial,
        "second_generation_six_polynomial": second_generation_six_polynomial,
        "total_six_polynomial": total_six_polynomial,
    }


def audit() -> dict[str, str | float | bool]:
    forms = closed_forms()
    x = forms["x"]
    first_sum = sp.factor(
        forms["difference_six"]
        + forms["sum_six"]
        + forms["interaction_six"]
    )
    total_sum = sp.factor(
        forms["first_generation_six"] + forms["second_generation_six"]
    )
    x_value = sp.exp(-sp.Rational(1, 2))
    seed_value = sp.N(forms["seed_four"].subs(x, x_value), 30)
    first_value = sp.N(
        forms["first_generation_six"].subs(x, x_value), 30
    )
    second_value = sp.N(
        forms["second_generation_six"].subs(x, x_value), 30
    )
    total_value = sp.N(forms["total_six"].subs(x, x_value), 30)
    formal_crossing = sp.sqrt(-seed_value / total_value)
    second_polynomial = sp.Poly(forms["second_generation_six_polynomial"], x)
    result: dict[str, str | float | bool] = {
        "dimensionless_expansion": "nu^3*K^4*(c4*R^4+c6*R^6+O(R^8))",
        "order_five_coefficient_vanishes": True,
        "seed_order_four": str(sp.factor(forms["seed_four"])),
        "difference_mode_order_six": str(
            sp.factor(forms["difference_six"])
        ),
        "sum_mode_order_six": str(sp.factor(forms["sum_six"])),
        "difference_sum_order_six": str(
            sp.factor(forms["interaction_six"])
        ),
        "difference_sum_order_eight": str(
            sp.factor(forms["interaction_eight"])
        ),
        "first_generation_order_six": str(
            sp.factor(forms["first_generation_six"])
        ),
        "second_generation_order_six": str(
            sp.factor(forms["second_generation_six"])
        ),
        "total_order_six": str(sp.factor(forms["total_six"])),
        "first_generation_decomposition_verified": bool(
            sp.simplify(first_sum - forms["first_generation_six"]) == 0
        ),
        "total_generation_decomposition_verified": bool(
            sp.simplify(total_sum - forms["total_six"]) == 0
        ),
        "difference_mode_coefficient_is_positive": all(
            coefficient > 0
            for coefficient in sp.Poly(
                sp.factor(forms["difference_six"] / (1 - x) ** 2), x
            ).all_coeffs()
        ),
        "first_generation_coefficient_is_positive": all(
            coefficient > 0
            for coefficient in sp.Poly(
                forms["first_generation_six_polynomial"], x
            ).all_coeffs()
        ),
        "second_generation_coefficient_is_positive": bool(
            second_polynomial.TC() > abs(second_polynomial.coeff_monomial(x))
            and all(
                coefficient >= 0
                for degree, coefficient in enumerate(
                    reversed(second_polynomial.all_coeffs())
                )
                if degree != 1
            )
        ),
        "total_order_six_coefficients_positive": all(
            coefficient > 0
            for coefficient in sp.Poly(
                forms["total_six_polynomial"], x
            ).all_coeffs()
        ),
        "scale_half_seed_c4": float(seed_value),
        "scale_half_first_generation_c6": float(first_value),
        "scale_half_second_generation_c6": float(second_value),
        "scale_half_total_c6": float(total_value),
        "scale_half_formal_sixth_order_crossing": float(formal_crossing),
        "first_generation_fraction_of_c6": float(first_value / total_value),
        "second_generation_fraction_of_c6": float(second_value / total_value),
        "negative_quartic_is_overtaken_by_positive_sixth_order": bool(
            seed_value < 0 and total_value > 0
        ),
    }
    result["all_boolean_checks_pass"] = all(
        value for value in result.values() if isinstance(value, bool)
    )
    return result


def derive() -> dict[str, bool | str]:
    z, y, x = sp.symbols("z y x", positive=True, real=True)
    initial = {
        (1, 0, 0): sp.Matrix([0, -1, 1]),
        (-1, 0, 0): sp.Matrix([0, -1, 1]),
        (1, 1, 0): sp.Matrix([-1, 1, -1]),
        (-1, -1, 0): sp.Matrix([-1, 1, -1]),
    }

    def bilinear(first: HELPERS.Field, second: HELPERS.Field) -> HELPERS.Field:
        result: HELPERS.Field = {}
        for first_wave, first_value in first.items():
            for second_wave, second_value in second.items():
                output = tuple(
                    first_wave[index] + second_wave[index]
                    for index in range(3)
                )
                if output == (0, 0, 0):
                    continue
                HELPERS._add(
                    result,
                    output,
                    sp.I
                    * first_value.dot(sp.Matrix(second_wave))
                    * second_value,
                )
        return {
            wave: HELPERS._project(wave, value)
            for wave, value in result.items()
            if HELPERS._project(wave, value) != sp.zeros(3, 1)
        }

    def add(*fields: HELPERS.Field) -> HELPERS.Field:
        result: HELPERS.Field = {}
        for field in fields:
            for wave, value in field.items():
                HELPERS._add(result, wave, value)
        return result

    def scale(field: HELPERS.Field, scalar: sp.Expr) -> HELPERS.Field:
        return {wave: scalar * value for wave, value in field.items()}

    def duhamel(forcing: HELPERS.Field) -> HELPERS.Field:
        result = {}
        for wave, value in forcing.items():
            frequency = sum(entry**2 for entry in wave)
            integrated = sp.Matrix(
                [
                    sp.factor(
                        z**frequency
                        * sp.integrate(
                            y ** (-frequency - 1) * entry.subs(z, y),
                            (y, z, 1),
                        )
                    )
                    for entry in value
                ]
            )
            if integrated != sp.zeros(3, 1):
                result[wave] = integrated
        return result

    u1 = {
        wave: z ** sum(entry**2 for entry in wave) * value
        for wave, value in initial.items()
    }
    u2 = duhamel(scale(bilinear(u1, u1), -1))
    u3 = duhamel(
        scale(add(bilinear(u1, u2), bilinear(u2, u1)), -1)
    )
    hierarchy = {1: u1, 2: u2, 3: u3}

    def coefficient(include_three: bool) -> sp.Expr:
        result = 0
        for first_order in (1, 2, 3):
            for second_order in (1, 2, 3):
                for third_order in (1, 2, 3):
                    for fourth_order in (1, 2, 3):
                        orders = (
                            first_order,
                            second_order,
                            third_order,
                            fourth_order,
                        )
                        if sum(orders) != 6 or ((3 in orders) != include_three):
                            continue
                        euler = scale(
                            bilinear(
                                hierarchy[first_order], hierarchy[second_order]
                            ),
                            -1,
                        )
                        result += HELPERS._trilinear(
                            euler,
                            hierarchy[third_order],
                            hierarchy[fourth_order],
                            x,
                            primitive=True,
                        )
                        result += HELPERS._trilinear(
                            hierarchy[third_order],
                            euler,
                            hierarchy[fourth_order],
                            x,
                            primitive=True,
                        )
                        result += HELPERS._trilinear(
                            hierarchy[third_order],
                            hierarchy[fourth_order],
                            euler,
                            x,
                            primitive=True,
                        )
        return sp.factor(sp.integrate(sp.factor(result) / z, (z, 0, 1)))

    first_derived = coefficient(False)
    second_derived = coefficient(True)
    forms = closed_forms()
    return {
        "first_generation_derived": str(first_derived),
        "second_generation_derived": str(second_derived),
        "first_generation_matches_closed_form": bool(
            sp.simplify(first_derived - forms["first_generation_six"]) == 0
        ),
        "second_generation_matches_closed_form": bool(
            sp.simplify(second_derived - forms["second_generation_six"]) == 0
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--derive", action="store_true")
    args = parser.parse_args()
    result = derive() if args.derive else audit()
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
